# Form implementation generated from reading ui file '/Users/thupham/PycharmProjects/KTLT_project/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1512, 861)
        self.label = QtWidgets.QLabel(parent=Login)
        self.label.setGeometry(QtCore.QRect(340, 110, 60, 16))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Login)
        self.label_2.setGeometry(QtCore.QRect(610, 220, 60, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_login = QtWidgets.QLabel(parent=Login)
        self.label_login.setGeometry(QtCore.QRect(0, 0, 1511, 861))
        self.label_login.setStyleSheet("\n"
"QMainWindow{\n"
"    border-image: url(p_Images/background.jpg) 0 0 0 0 stretch stretch;\n"
"}\n"
"")
        self.label_login.setText("")
        self.label_login.setPixmap(QtGui.QPixmap("/Users/thupham/PycharmProjects/KTLT_project/p_Images/login.png"))
        self.label_login.setScaledContents(True)
        self.label_login.setObjectName("label_login")
        self.btn_minimize = QtWidgets.QPushButton(parent=Login)
        self.btn_minimize.setGeometry(QtCore.QRect(1360, 10, 41, 32))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_maximize = QtWidgets.QPushButton(parent=Login)
        self.btn_maximize.setGeometry(QtCore.QRect(1400, 10, 41, 32))
        self.btn_maximize.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(parent=Login)
        self.btn_close.setGeometry(QtCore.QRect(1440, 10, 41, 32))
        self.btn_close.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:red;\n"
"                           color:white;\n"
"                       }")
        self.btn_close.setObjectName("btn_close")
        self.loginFrame = QtWidgets.QFrame(parent=Login)
        self.loginFrame.setGeometry(QtCore.QRect(450, 190, 531, 441))
        self.loginFrame.setStyleSheet("background-color: white;\n"
"border-radius: 30px;")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.lb_tendangnhap = QtWidgets.QLabel(parent=self.loginFrame)
        self.lb_tendangnhap.setGeometry(QtCore.QRect(160, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lb_tendangnhap.setFont(font)
        self.lb_tendangnhap.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_tendangnhap.setObjectName("lb_tendangnhap")
        self.LineE_tendangnhap = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.LineE_tendangnhap.setGeometry(QtCore.QRect(90, 70, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.LineE_tendangnhap.setFont(font)
        self.LineE_tendangnhap.setStyleSheet("border: none;\n"
"border-radius: 22px;\n"
"padding: 12px;\n"
"background-color: #EEF5F1;\n"
"font-size: 15px;\n"
"background-color: white;\n"
"border: 1px solid #9EC9B7;\n"
"\n"
"")
        self.LineE_tendangnhap.setText("")
        self.LineE_tendangnhap.setObjectName("LineE_tendangnhap")
        self.LineE_matkhau = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.LineE_matkhau.setGeometry(QtCore.QRect(90, 190, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.LineE_matkhau.setFont(font)
        self.LineE_matkhau.setStyleSheet("border: none;\n"
"border-radius: 22px;\n"
"padding: 12px;\n"
"background-color: #EEF5F1;\n"
"font-size: 15px;\n"
"background-color: white;\n"
"border: 1px solid #9EC9B7;")
        self.LineE_matkhau.setInputMask("")
        self.LineE_matkhau.setText("")
        self.LineE_matkhau.setObjectName("LineE_matkhau")
        self.lb_matkhau = QtWidgets.QLabel(parent=self.loginFrame)
        self.lb_matkhau.setGeometry(QtCore.QRect(180, 150, 151, 31))
        self.lb_matkhau.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_matkhau.setObjectName("lb_matkhau")
        self.pB_dangnhap = QtWidgets.QPushButton(parent=self.loginFrame)
        self.pB_dangnhap.setGeometry(QtCore.QRect(90, 270, 331, 51))
        self.pB_dangnhap.setMinimumSize(QtCore.QSize(45, 45))
        self.pB_dangnhap.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}\n"
"QPushButton {\n"
"    background-color: #63B995;\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4FA883;\n"
"}\n"
"")
        self.pB_dangnhap.setObjectName("pB_dangnhap")
        self.pB_quenmk = QtWidgets.QPushButton(parent=self.loginFrame)
        self.pB_quenmk.setGeometry(QtCore.QRect(50, 380, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pB_quenmk.setFont(font)
        self.pB_quenmk.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pB_quenmk.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: #5c7f6e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"    color: #3e5f52;\n"
"}\n"
"QLabel:hover {\n"
"    color: #4FA883;\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.pB_quenmk.setFlat(True)
        self.pB_quenmk.setObjectName("pB_quenmk")
        self.pB_dangky = QtWidgets.QPushButton(parent=self.loginFrame)
        self.pB_dangky.setGeometry(QtCore.QRect(340, 380, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pB_dangky.setFont(font)
        self.pB_dangky.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pB_dangky.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: #5c7f6e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"    color: #3e5f52;\n"
"}\n"
"")
        self.pB_dangky.setFlat(True)
        self.pB_dangky.setObjectName("pB_dangky")
        self.lb_error = QtWidgets.QLabel(parent=self.loginFrame)
        self.lb_error.setGeometry(QtCore.QRect(100, 250, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_error.setFont(font)
        self.lb_error.setStyleSheet("color: red;\n"
"font-size: 14px;")
        self.lb_error.setText("")
        self.lb_error.setObjectName("lb_error")
        self.btn_eye = QtWidgets.QPushButton(parent=self.loginFrame)
        self.btn_eye.setGeometry(QtCore.QRect(360, 200, 30, 30))
        self.btn_eye.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_eye.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_eye.setText("")
        self.btn_eye.setObjectName("btn_eye")
        self.lbl_error = QtWidgets.QLabel(parent=self.loginFrame)
        self.lbl_error.setGeometry(QtCore.QRect(110, 340, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(14)
        self.lbl_error.setFont(font)
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.btn_minimize.setText(_translate("Login", "-"))
        self.btn_maximize.setText(_translate("Login", "□"))
        self.btn_close.setText(_translate("Login", "x"))
        self.lb_tendangnhap.setText(_translate("Login", "      Tên đăng nhập "))
        self.LineE_tendangnhap.setPlaceholderText(_translate("Login", "                     Nhập tên đăng nhập"))
        self.LineE_matkhau.setPlaceholderText(_translate("Login", "                         Nhập mật khẩu"))
        self.lb_matkhau.setText(_translate("Login", "       Mật khẩu"))
        self.pB_dangnhap.setText(_translate("Login", "ĐĂNG NHẬP "))
        self.pB_quenmk.setText(_translate("Login", "Quên mật khẩu?"))
        self.pB_dangky.setText(_translate("Login", "Đăng ký"))
