# Form implementation generated from reading ui file 'D:\PythonProjects\MindfulStudy\focus.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 722)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 951, 671))
        self.label.setStyleSheet("resetBtn_2 {\n"
"    background-color: #7FBF9F;  \n"
"    color: white;               \n"
"    border-radius: 22px;        \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"resetBtn_2:hover {\n"
"    background-color: #5FA382; \n"
"}\n"
"\n"
"resetBtn_2:pressed {\n"
"    background-color: #4E8C70;  \n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Bong Nguyen.BONGNGUYEN/Downloads/Green Pastel Watercolor Playful Project Proposal Presentation (2).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.focusBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.focusBtn.setGeometry(QtCore.QRect(340, 140, 250, 250))
        self.focusBtn.setMinimumSize(QtCore.QSize(150, 150))
        self.focusBtn.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.focusBtn.setFont(font)
        self.focusBtn.setStyleSheet("#focusBtn {\n"
"    background-color: #F8BBD0;\n"
"    color: green;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    border-radius: 125px;\n"
"}\n"
"\n"
"#focusBtn:pressed {\n"
"    background-color: #F48FB1;\n"
"}                                                                                                   #focusBtn:hover {\n"
"    background-color: #F48FB1;\n"
"}")
        self.focusBtn.setObjectName("focusBtn")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 430, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.timeEdit_2 = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timeEdit_2.setGeometry(QtCore.QRect(410, 420, 131, 41))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.resetBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetBtn_2.setGeometry(QtCore.QRect(260, 490, 150, 41))
        self.resetBtn_2.setStyleSheet("#resetBtn_2 {\n"
"    background-color: #7FBF9F;   \n"
"    color: white;                \n"
"    border-radius: 22px;         \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"#resetBtn_2:hover {\n"
"    background-color: #5FA382;   \n"
"}\n"
"\n"
"#resetBtn_2:pressed {\n"
"    background-color: #4E8C70;   \n"
"}")
        self.resetBtn_2.setObjectName("resetBtn_2")
        self.reportBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reportBtn_2.setGeometry(QtCore.QRect(510, 490, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.reportBtn_2.setFont(font)
        self.reportBtn_2.setStyleSheet("#reportBtn_2 {\n"
"    background-color: #7FBF9F;   \n"
"    color: white;                \n"
"    border-radius: 22px;         \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"#reportBtn_2:hover {\n"
"    background-color: #5FA382;   \n"
"}\n"
"\n"
"#reportBtn_2:pressed {\n"
"    background-color: #4E8C70;   \n"
"}")
        self.reportBtn_2.setObjectName("reportBtn_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 540, 801, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.minimize_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minimize_btn.setGeometry(QtCore.QRect(830, 0, 41, 21))
        self.minimize_btn.setText("")
        self.minimize_btn.setObjectName("minimize_btn")
        self.maximize_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.maximize_btn.setGeometry(QtCore.QRect(870, 0, 41, 21))
        self.maximize_btn.setText("")
        self.maximize_btn.setObjectName("maximize_btn")
        self.close_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(910, 0, 41, 21))
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.focusBtn.setText(_translate("MainWindow", "FOCUS"))
        self.label_5.setText(_translate("MainWindow", "Thời gian:"))
        self.timeEdit_2.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.resetBtn_2.setText(_translate("MainWindow", "RESET"))
        self.reportBtn_2.setText(_translate("MainWindow", "XUẤT BÁO CÁO"))
        self.label_2.setText(_translate("MainWindow", "\"Học tập là chìa khóa mở ra tương lai, là ngọn lửa cháy mãi trong tâm hồn và vũ khí mạnh nhất để thay đổi thế giới.\""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
