# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mindfulstudy(object):
    def setupUi(self, Mindfulstudy):
        Mindfulstudy.setObjectName("Mindfulstudy")
        Mindfulstudy.resize(1081, 885)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mindfulstudy.sizePolicy().hasHeightForWidth())
        Mindfulstudy.setSizePolicy(sizePolicy)
        Mindfulstudy.setStyleSheet("#centralwidget {\n"
"    border-image: url(\"C:/Users/nguye/OneDrive/Pictures/Screenshots/Ảnh chụp màn hình 2026-03-09 213120.png\") 0 0 0 0 stretch stretch;\n"
"}")
        Mindfulstudy.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=Mindfulstudy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_9.setStyleSheet("QFrame {\n"
"    background-color: transparent; /* Làm trong suốt màu nền 100% */\n"
"    border: none;                  /* Xóa luôn cái đường viền (nếu có) để khỏi bị gạch chéo */\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(953, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_9)
        self.frame_7.setMaximumSize(QtCore.QSize(151, 52))
        self.frame_7.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: transparent; /* Làm trong suốt màu nền 100% */\n"
"    border: none;                  /* Xóa luôn cái đường viền (nếu có) để khỏi bị gạch chéo */\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(parent=self.frame_7)
        self.btn_minimize.setMaximumSize(QtCore.QSize(41, 28))
        self.btn_minimize.setStyleSheet("\n"
"               QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:#E0E0E0;\n"
"               }\n"
"               \"\"\")\n"
"")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(parent=self.frame_7)
        self.btn_maximize.setMaximumSize(QtCore.QSize(41, 28))
        self.btn_maximize.setStyleSheet("QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:#E0E0E0;\n"
"               }\n"
"               ")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_5.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame_7)
        self.btn_close.setMaximumSize(QtCore.QSize(41, 28))
        self.btn_close.setStyleSheet("QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:red;\n"
"                   color:white;\n"
"               }")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_deadlines = QtWidgets.QPushButton(parent=self.frame)
        self.btn_deadlines.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_deadlines.setObjectName("btn_deadlines")
        self.verticalLayout.addWidget(self.btn_deadlines)
        self.btn_thoikhoabieu = QtWidgets.QPushButton(parent=self.frame)
        self.btn_thoikhoabieu.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_thoikhoabieu.setObjectName("btn_thoikhoabieu")
        self.verticalLayout.addWidget(self.btn_thoikhoabieu)
        self.btn_taptrung = QtWidgets.QPushButton(parent=self.frame)
        self.btn_taptrung.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_taptrung.setObjectName("btn_taptrung")
        self.verticalLayout.addWidget(self.btn_taptrung)
        self.btn_baocaonangsuat = QtWidgets.QPushButton(parent=self.frame)
        self.btn_baocaonangsuat.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_baocaonangsuat.setObjectName("btn_baocaonangsuat")
        self.verticalLayout.addWidget(self.btn_baocaonangsuat)
        self.btn_nhatky = QtWidgets.QPushButton(parent=self.frame)
        self.btn_nhatky.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_nhatky.setObjectName("btn_nhatky")
        self.verticalLayout.addWidget(self.btn_nhatky)
        self.btn_dethi = QtWidgets.QPushButton(parent=self.frame)
        self.btn_dethi.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_dethi.setObjectName("btn_dethi")
        self.verticalLayout.addWidget(self.btn_dethi)
        self.horizontalLayout_3.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"    background-color: rgba(255, 255, 255, 120); /* Màu trắng mờ như kính */\n"
"    border-radius: 20px;\n"
"    border: 1px solid rgba(255, 255, 255, 150);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_1)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_8.setMaximumSize(QtCore.QSize(223, 46))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.frame_8)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lbl_nhiemvu = QtWidgets.QLabel(parent=self.frame_8)
        self.lbl_nhiemvu.setStyleSheet("QLabel {\n"
"    color: #5D4037; /* Màu nâu đất */ \n"
"    font-family: \"Avenir Next \", sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.lbl_nhiemvu.setObjectName("lbl_nhiemvu")
        self.horizontalLayout_6.addWidget(self.lbl_nhiemvu)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.listWidget_nv = QtWidgets.QListWidget(parent=self.frame_2)
        self.listWidget_nv.setEnabled(True)
        self.listWidget_nv.setStyleSheet("QListWidget {\n"
"    background-color: rgba(255, 255, 255, 180); \n"
"    border-radius: 10px;\n"
"    border: 1px solid #DCE3D5;\n"
"    color: #4a5c4d; /* Màu xanh đậm */\n"
"    font-size: 16px;\n"
"    font-family:\"Avenir Next\";\n"
"    padding: 10px;\n"
"}\n"
"/* Lúc bấm vào 1 công việc thì nó hiện màu xanh lá */\n"
"QListWidget::item:selected {\n"
"    background-color: #8db596;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}")
        self.listWidget_nv.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidget_nv.setObjectName("listWidget_nv")
        self.verticalLayout_2.addWidget(self.listWidget_nv)
        self.lineEdit_nv = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_nv.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #8db596;\n"
"    border-radius: 15px;\n"
"    padding: 8px 15px;\n"
"    font-size: 14px;\n"
"    font-family:\"Avenir Next\";\n"
"    color: #4a5c4d;\n"
"}")
        self.lineEdit_nv.setText("")
        self.lineEdit_nv.setObjectName("lineEdit_nv")
        self.verticalLayout_2.addWidget(self.lineEdit_nv)
        self.btn_them1 = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_them1.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_them1.setObjectName("btn_them1")
        self.verticalLayout_2.addWidget(self.btn_them1)
        self.btn_xoa1 = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_xoa1.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_xoa1.setObjectName("btn_xoa1")
        self.verticalLayout_2.addWidget(self.btn_xoa1)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_quanlydl = QtWidgets.QLabel(parent=self.page_2)
        self.lbl_quanlydl.setStyleSheet("QLabel {\n"
"    color: #5D4037; /* Màu nâu đất */ \n"
"    font-family: \"Anenir Next\", sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.lbl_quanlydl.setObjectName("lbl_quanlydl")
        self.verticalLayout_4.addWidget(self.lbl_quanlydl)
        self.frame_3 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_dl = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_dl.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #8db596;\n"
"    border-radius: 15px;\n"
"    padding: 8px 15px;\n"
"    font-size: 14px;\n"
"    font-family:\"Avenir Next\";\n"
"    color: #4a5c4d;\n"
"}")
        self.lineEdit_dl.setObjectName("lineEdit_dl")
        self.horizontalLayout.addWidget(self.lineEdit_dl)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("QDateTimeEdit {\n"
"    font-family: \"Avenir Next\"; \n"
"    font-size: 14px; /\n"
"    font-weight: 500;\n"
"    color: #4a5c4d; /* Màu chữ xanh đậm*/\n"
"    background-color: white;\n"
"    border: 2px solid #8db596; /* Viền xanh lá y chang ô nhập */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px 10px; /* Tạo độ phồng */\n"
"}\n"
"\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover {\n"
"    background-color: #DCE3D5;\n"
"    border-radius: 5px;\n"
"}")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout.addWidget(self.dateTimeEdit)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_them2 = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_them2.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_them2.setObjectName("btn_them2")
        self.horizontalLayout_2.addWidget(self.btn_them2)
        self.btn_luu = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_luu.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_luu.setObjectName("btn_luu")
        self.horizontalLayout_2.addWidget(self.btn_luu)
        self.btn_xoa2 = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_xoa2.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_xoa2.setObjectName("btn_xoa2")
        self.horizontalLayout_2.addWidget(self.btn_xoa2)
        self.btn_dong = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_dong.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btn_dong.setObjectName("btn_dong")
        self.horizontalLayout_2.addWidget(self.btn_dong)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.listWidget_dl = QtWidgets.QListWidget(parent=self.page_2)
        self.listWidget_dl.setStyleSheet("QListWidget {\n"
"    background-color: rgba(255, 255, 255, 180); \n"
"    border-radius: 10px;\n"
"    border: 1px solid #DCE3D5;\n"
"    color: #4a5c4d; /* Màu xanh đậm */\n"
"    font-size: 16px;\n"
"    font-family:\"Avenir Next\";\n"
"    padding: 10px;\n"
"}\n"
"/* Lúc bấm vào 1 công việc thì nó hiện màu xanh lá */\n"
"QListWidget::item:selected {\n"
"    background-color: #8db596;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}")
        self.listWidget_dl.setObjectName("listWidget_dl")
        self.verticalLayout_4.addWidget(self.listWidget_dl)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_thoikhoabieu = QtWidgets.QLabel(parent=self.frame_4)
        self.lbl_thoikhoabieu.setStyleSheet("QLabel {\n"
"    color: #5D4037; /* Màu nâu đất */ \n"
"    font-family: \"Avenir Next\", sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.lbl_thoikhoabieu.setObjectName("lbl_thoikhoabieu")
        self.verticalLayout_6.addWidget(self.lbl_thoikhoabieu)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame_4)
        self.tableWidget.setStyleSheet("\n"
"QHeaderView::section:vertical {\n"
"    background-color: #7FBF9F ;\n"
"    color: white;\n"
"    font-family: \"Avenir Next\";\n"
"    font-weight: bold;\n"
"    border: 1px solid #7a9e82;\n"
"    padding: 8px;\n"
"}")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(68)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(32)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbl_taptrung = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_taptrung.setStyleSheet("QLabel {\n"
"    color: #5D4037; /* Màu nâu đất */ \n"
"    font-family: \"Avenir Next \", sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.lbl_taptrung.setObjectName("lbl_taptrung")
        self.verticalLayout_8.addWidget(self.lbl_taptrung)
        self.lbl_chonnhiemvu = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_chonnhiemvu.setStyleSheet("QLabel {\n"
"    background-color: white; \n"
"    border: 2px dashed #8db596; \n"
"    border-radius: 15px;\n"
"    padding: 20px; \n"
"    font-size: 28px;\n"
"    color: #4a5c4d; /* Màu xanh lá đậm */\n"
"    font-weight: bold;\n"
"    font-family: \"Avenir Next\", sans-serif;\n"
"}")
        self.lbl_chonnhiemvu.setObjectName("lbl_chonnhiemvu")
        self.verticalLayout_8.addWidget(self.lbl_chonnhiemvu)
        self.listWidget_taptrung = QtWidgets.QListWidget(parent=self.page_4)
        self.listWidget_taptrung.setStyleSheet("QListWidget {\n"
"    background-color: rgba(255, 255, 255, 180); \n"
"    border-radius: 10px;\n"
"    border: 1px solid #DCE3D5;\n"
"    color: #4a5c4d; /* Màu xanh đậm */\n"
"    font-size: 16px;\n"
"    font-family:\"Avenir Next\";\n"
"    padding: 10px;\n"
"}\n"
"/* Lúc bấm vào 1 công việc thì nó hiện màu xanh lá */\n"
"QListWidget::item:selected {\n"
"    background-color: #8db596;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}")
        self.listWidget_taptrung.setObjectName("listWidget_taptrung")
        self.verticalLayout_8.addWidget(self.listWidget_taptrung)
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        Mindfulstudy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Mindfulstudy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 26))
        self.menubar.setObjectName("menubar")
        Mindfulstudy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Mindfulstudy)
        self.statusbar.setObjectName("statusbar")
        Mindfulstudy.setStatusBar(self.statusbar)

        self.retranslateUi(Mindfulstudy)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Mindfulstudy)

    def retranslateUi(self, Mindfulstudy):
        _translate = QtCore.QCoreApplication.translate
        Mindfulstudy.setWindowTitle(_translate("Mindfulstudy", "Mindful study "))
        self.btn_minimize.setText(_translate("Mindfulstudy", "–"))
        self.btn_maximize.setText(_translate("Mindfulstudy", "□"))
        self.btn_close.setText(_translate("Mindfulstudy", "×"))
        self.btn_deadlines.setText(_translate("Mindfulstudy", "⏳ Deadlines "))
        self.btn_thoikhoabieu.setText(_translate("Mindfulstudy", "🗓️  Thời khóa biểu"))
        self.btn_taptrung.setText(_translate("Mindfulstudy", "📌 Chế độ tập trung "))
        self.btn_baocaonangsuat.setText(_translate("Mindfulstudy", "📊 Báo cáo năng suất "))
        self.btn_nhatky.setText(_translate("Mindfulstudy", "🥰 Nhật ký cảm xúc "))
        self.btn_dethi.setText(_translate("Mindfulstudy", "📄 Đề thi "))
        self.label.setText(_translate("Mindfulstudy", "📝"))
        self.lbl_nhiemvu.setText(_translate("Mindfulstudy", "Nhiệm vụ hôm nay "))
        self.btn_them1.setText(_translate("Mindfulstudy", "Thêm"))
        self.btn_xoa1.setText(_translate("Mindfulstudy", "Xóa "))
        self.lbl_quanlydl.setText(_translate("Mindfulstudy", "Quản lý deadlines"))
        self.btn_them2.setText(_translate("Mindfulstudy", "Thêm"))
        self.btn_luu.setText(_translate("Mindfulstudy", "Lưu"))
        self.btn_xoa2.setText(_translate("Mindfulstudy", "Xóa"))
        self.btn_dong.setText(_translate("Mindfulstudy", "Đóng "))
        self.lbl_thoikhoabieu.setText(_translate("Mindfulstudy", "Thời khóa biểu"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Mindfulstudy", "Sáng"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Mindfulstudy", "Chiều  "))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Mindfulstudy", "Tối "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Mindfulstudy", "Thứ 2"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Mindfulstudy", "Thứ 3"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Mindfulstudy", "Thứ 4"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Mindfulstudy", "Thứ 5 "))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Mindfulstudy", "Thứ 6"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Mindfulstudy", "Thứ 7"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Mindfulstudy", "CN"))
        self.lbl_taptrung.setText(_translate("Mindfulstudy", "Bạn đang tập trung vào: "))
        self.lbl_chonnhiemvu.setText(_translate("Mindfulstudy", "Nhiệm vụ được chọn:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mindfulstudy = QtWidgets.QMainWindow()
    ui = Ui_Mindfulstudy()
    ui.setupUi(Mindfulstudy)
    Mindfulstudy.show()
    sys.exit(app.exec())
