# Form implementation generated from reading ui file '/Users/thupham/PycharmProjects/KTLT_project/register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1512, 861)
        Register.setStyleSheet("\n"
"QMainWindow{\n"
"    border-image: url(p_Images/background.jpg) 0 0 0 0 stretch stretch;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(parent=Register)
        self.label.setGeometry(QtCore.QRect(0, 0, 1511, 871))
        self.label.setStyleSheet("QMainWindow{\n"
"                        border-image: url(p_Images/login.png) 0 0 0 0 stretch stretch;\n"
"                    }")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/thupham/PycharmProjects/KTLT_project/p_Images/Green Pastel Watercolor Playful Project Proposal Presentation (10).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_background = QtWidgets.QLabel(parent=Register)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1511, 861))
        self.label_background.setStyleSheet("background-image: url(background.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("/Users/thupham/PycharmProjects/KTLT_project/p_Images/background.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.btn_minimize = QtWidgets.QPushButton(parent=Register)
        self.btn_minimize.setGeometry(QtCore.QRect(1370, 10, 41, 32))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_maximize = QtWidgets.QPushButton(parent=Register)
        self.btn_maximize.setGeometry(QtCore.QRect(1410, 10, 41, 32))
        self.btn_maximize.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(parent=Register)
        self.btn_close.setGeometry(QtCore.QRect(1450, 10, 41, 32))
        self.btn_close.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:red;\n"
"                           color:white;\n"
"                       }\n"
"                    ")
        self.btn_close.setObjectName("btn_close")
        self.RegisterFrame = QtWidgets.QFrame(parent=Register)
        self.RegisterFrame.setGeometry(QtCore.QRect(460, 30, 581, 741))
        self.RegisterFrame.setStyleSheet("background-color: white;\n"
"border-radius: 30px;")
        self.RegisterFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.RegisterFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RegisterFrame.setObjectName("RegisterFrame")
        self.lb_hovaten = QtWidgets.QLabel(parent=self.RegisterFrame)
        self.lb_hovaten.setGeometry(QtCore.QRect(130, 100, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lb_hovaten.setFont(font)
        self.lb_hovaten.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_hovaten.setObjectName("lb_hovaten")
        self.LineE_hovaten = QtWidgets.QLineEdit(parent=self.RegisterFrame)
        self.LineE_hovaten.setGeometry(QtCore.QRect(120, 150, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(-1)
        self.LineE_hovaten.setFont(font)
        self.LineE_hovaten.setStyleSheet("border: none;\n"
"border-radius: 22px;\n"
"padding: 12px;\n"
"background-color: #EEF5F1;\n"
"font-size: 15px;\n"
"background-color: white;\n"
"border: 1px solid #9EC9B7;\n"
"font-family: \"Avenir Next\";\n"
"\n"
"\n"
"")
        self.LineE_hovaten.setText("")
        self.LineE_hovaten.setObjectName("LineE_hovaten")
        self.pB_dangky = QtWidgets.QPushButton(parent=self.RegisterFrame)
        self.pB_dangky.setGeometry(QtCore.QRect(60, 580, 451, 51))
        self.pB_dangky.setMinimumSize(QtCore.QSize(45, 45))
        self.pB_dangky.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}\n"
"QPushButton {\n"
"    background-color: #63B995;\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4FA883;\n"
"}\n"
"")
        self.pB_dangky.setObjectName("pB_dangky")
        self.pB_dangnhap = QtWidgets.QPushButton(parent=self.RegisterFrame)
        self.pB_dangnhap.setGeometry(QtCore.QRect(290, 690, 91, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pB_dangnhap.setFont(font)
        self.pB_dangnhap.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pB_dangnhap.setStyleSheet("QPushButton {\n"
"            border: none;\n"
"            background: transparent;\n"
"            color: #2F4F4F;\n"
"            font-weight: bold;\n"
"            font-size:15px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            text-decoration: underline;\n"
"            color: #1f3d3a;\n"
"        }")
        self.pB_dangnhap.setFlat(True)
        self.pB_dangnhap.setObjectName("pB_dangnhap")
        self.lb_matkhau = QtWidgets.QLabel(parent=self.RegisterFrame)
        self.lb_matkhau.setGeometry(QtCore.QRect(130, 330, 151, 31))
        self.lb_matkhau.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_matkhau.setObjectName("lb_matkhau")
        self.LineE_matkhau = QtWidgets.QLineEdit(parent=self.RegisterFrame)
        self.LineE_matkhau.setGeometry(QtCore.QRect(120, 370, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(-1)
        self.LineE_matkhau.setFont(font)
        self.LineE_matkhau.setStyleSheet("border: none;\n"
"border-radius: 22px;\n"
"padding: 12px;\n"
"background-color: #EEF5F1;\n"
"font-size: 15px;\n"
"background-color: white;\n"
"border: 1px solid #9EC9B7;\n"
"font-family: \"Avenir Next\";")
        self.LineE_matkhau.setInputMask("")
        self.LineE_matkhau.setText("")
        self.LineE_matkhau.setObjectName("LineE_matkhau")
        self.lb_xacnhan = QtWidgets.QLabel(parent=self.RegisterFrame)
        self.lb_xacnhan.setGeometry(QtCore.QRect(130, 450, 161, 31))
        self.lb_xacnhan.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_xacnhan.setObjectName("lb_xacnhan")
        self.LineE_xacnhan = QtWidgets.QLineEdit(parent=self.RegisterFrame)
        self.LineE_xacnhan.setGeometry(QtCore.QRect(120, 500, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(-1)
        self.LineE_xacnhan.setFont(font)
        self.LineE_xacnhan.setStyleSheet("border: none;\n"
"border-radius: 22px;\n"
"padding: 12px;\n"
"background-color: #EEF5F1;\n"
"font-size: 15px;\n"
"background-color: white;\n"
"border: 1px solid #9EC9B7;\n"
"font-family: \"Avenir Next\";")
        self.LineE_xacnhan.setInputMask("")
        self.LineE_xacnhan.setText("")
        self.LineE_xacnhan.setObjectName("LineE_xacnhan")
        self.label_daco = QtWidgets.QLabel(parent=self.RegisterFrame)
        self.label_daco.setGeometry(QtCore.QRect(170, 700, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(15)
        self.label_daco.setFont(font)
        self.label_daco.setObjectName("label_daco")
        self.lb_tendangnhap = QtWidgets.QLabel(parent=self.RegisterFrame)
        self.lb_tendangnhap.setGeometry(QtCore.QRect(130, 220, 151, 31))
        self.lb_tendangnhap.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_tendangnhap.setObjectName("lb_tendangnhap")
        self.LineE_tendangnhap = QtWidgets.QLineEdit(parent=self.RegisterFrame)
        self.LineE_tendangnhap.setGeometry(QtCore.QRect(120, 260, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(-1)
        self.LineE_tendangnhap.setFont(font)
        self.LineE_tendangnhap.setStyleSheet("border: none;\n"
"border-radius: 22px;\n"
"padding: 12px;\n"
"background-color: #EEF5F1;\n"
"font-size: 15px;\n"
"background-color: white;\n"
"border: 1px solid #9EC9B7;\n"
"font-family: \"Avenir Next\";")
        self.LineE_tendangnhap.setInputMask("")
        self.LineE_tendangnhap.setText("")
        self.LineE_tendangnhap.setObjectName("LineE_tendangnhap")
        self.frame_dangky = QtWidgets.QFrame(parent=self.RegisterFrame)
        self.frame_dangky.setGeometry(QtCore.QRect(-30, 0, 631, 61))
        self.frame_dangky.setStyleSheet("\n"
"background-color:#EAF5F0;\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"")
        self.frame_dangky.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_dangky.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_dangky.setObjectName("frame_dangky")
        self.label_dangky = QtWidgets.QLabel(parent=self.frame_dangky)
        self.label_dangky.setGeometry(QtCore.QRect(270, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_dangky.setFont(font)
        self.label_dangky.setStyleSheet("color:#5F7F73;")
        self.label_dangky.setObjectName("label_dangky")
        self.lbl_error = QtWidgets.QLabel(parent=self.RegisterFrame)
        self.lbl_error.setGeometry(QtCore.QRect(70, 640, 431, 31))
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")
        self.btn_eye_password = QtWidgets.QPushButton(parent=self.RegisterFrame)
        self.btn_eye_password.setGeometry(QtCore.QRect(400, 390, 31, 21))
        self.btn_eye_password.setText("")
        self.btn_eye_password.setIconSize(QtCore.QSize(18, 18))
        self.btn_eye_password.setFlat(True)
        self.btn_eye_password.setObjectName("btn_eye_password")
        self.btn_eye_confirm = QtWidgets.QPushButton(parent=self.RegisterFrame)
        self.btn_eye_confirm.setGeometry(QtCore.QRect(400, 520, 31, 21))
        self.btn_eye_confirm.setText("")
        self.btn_eye_confirm.setIconSize(QtCore.QSize(18, 18))
        self.btn_eye_confirm.setFlat(True)
        self.btn_eye_confirm.setObjectName("btn_eye_confirm")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Dialog"))
        self.btn_minimize.setText(_translate("Register", "-"))
        self.btn_maximize.setText(_translate("Register", "□"))
        self.btn_close.setText(_translate("Register", "x"))
        self.lb_hovaten.setText(_translate("Register", "Họ và tên"))
        self.LineE_hovaten.setPlaceholderText(_translate("Register", "Nhập họ và tên"))
        self.pB_dangky.setText(_translate("Register", "ĐĂNG KÝ"))
        self.pB_dangnhap.setText(_translate("Register", "Đăng nhập"))
        self.lb_matkhau.setText(_translate("Register", "Mật khẩu"))
        self.LineE_matkhau.setPlaceholderText(_translate("Register", "Nhập mật khẩu"))
        self.lb_xacnhan.setText(_translate("Register", "Xác nhận mật khẩu"))
        self.LineE_xacnhan.setPlaceholderText(_translate("Register", "Xác nhận mật khẩu"))
        self.label_daco.setText(_translate("Register", "Đã có tài khoản?"))
        self.lb_tendangnhap.setText(_translate("Register", "Tên đăng nhập"))
        self.LineE_tendangnhap.setPlaceholderText(_translate("Register", "Nhập tên đăng nhập "))
        self.label_dangky.setText(_translate("Register", "ĐĂNG KÝ"))
