# Form implementation generated from reading ui file '/Users/thupham/PycharmProjects/KTLT_project/reset.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reset(object):
    def setupUi(self, Reset):
        Reset.setObjectName("Reset")
        Reset.resize(1512, 861)
        self.reset = QtWidgets.QLabel(parent=Reset)
        self.reset.setGeometry(QtCore.QRect(0, -90, 1511, 951))
        self.reset.setStyleSheet("QMainWindow{\n"
"                        border-image: url(p_Images/login.png) 0 0 0 0 stretch stretch;\n"
"                    }")
        self.reset.setText("")
        self.reset.setPixmap(QtGui.QPixmap("/Users/thupham/PycharmProjects/KTLT_project/p_Images/Green Pastel Watercolor Playful Project Proposal Presentation (10).png"))
        self.reset.setScaledContents(True)
        self.reset.setObjectName("reset")
        self.label_background = QtWidgets.QLabel(parent=Reset)
        self.label_background.setGeometry(QtCore.QRect(-10, 0, 1521, 861))
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("/Users/thupham/PycharmProjects/KTLT_project/p_Images/background.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.btn_minimize = QtWidgets.QPushButton(parent=Reset)
        self.btn_minimize.setGeometry(QtCore.QRect(1360, 10, 51, 41))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }\n"
"                       ")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_maximize = QtWidgets.QPushButton(parent=Reset)
        self.btn_maximize.setGeometry(QtCore.QRect(1410, 10, 51, 41))
        self.btn_maximize.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }\n"
"                       ")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(parent=Reset)
        self.btn_close.setGeometry(QtCore.QRect(1450, 10, 51, 41))
        self.btn_close.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:transparent;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:red;\n"
"                           color:white;\n"
"                       }")
        self.btn_close.setObjectName("btn_close")
        self.ResetFrame = QtWidgets.QFrame(parent=Reset)
        self.ResetFrame.setGeometry(QtCore.QRect(520, 100, 541, 521))
        self.ResetFrame.setStyleSheet("border-radius: 30px;\n"
"background-color: white;")
        self.ResetFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ResetFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ResetFrame.setObjectName("ResetFrame")
        self.frame_khoiphuc = QtWidgets.QFrame(parent=self.ResetFrame)
        self.frame_khoiphuc.setGeometry(QtCore.QRect(-20, 0, 621, 61))
        self.frame_khoiphuc.setStyleSheet("\n"
"background-color:#EAF5F0;\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"")
        self.frame_khoiphuc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_khoiphuc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_khoiphuc.setObjectName("frame_khoiphuc")
        self.label_khoiphuc = QtWidgets.QLabel(parent=self.frame_khoiphuc)
        self.label_khoiphuc.setGeometry(QtCore.QRect(190, 20, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_khoiphuc.setFont(font)
        self.label_khoiphuc.setStyleSheet("color:#5F7F73;")
        self.label_khoiphuc.setObjectName("label_khoiphuc")
        self.lineEdit_tendangnhap = QtWidgets.QLineEdit(parent=self.ResetFrame)
        self.lineEdit_tendangnhap.setGeometry(QtCore.QRect(30, 120, 431, 41))
        self.lineEdit_tendangnhap.setStyleSheet("\n"
"border:2px solid #8EC5B7;\n"
"border-radius:20px;\n"
"padding-left:35px;\n"
"background:white;\n"
"font-family: \"Avenir Next\";\n"
"font-size:15px;")
        self.lineEdit_tendangnhap.setText("")
        self.lineEdit_tendangnhap.setObjectName("lineEdit_tendangnhap")
        self.lb_tendangnhap = QtWidgets.QLabel(parent=self.ResetFrame)
        self.lb_tendangnhap.setGeometry(QtCore.QRect(10, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lb_tendangnhap.setFont(font)
        self.lb_tendangnhap.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_tendangnhap.setObjectName("lb_tendangnhap")
        self.lb_matkhau = QtWidgets.QLabel(parent=self.ResetFrame)
        self.lb_matkhau.setGeometry(QtCore.QRect(30, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lb_matkhau.setFont(font)
        self.lb_matkhau.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_matkhau.setObjectName("lb_matkhau")
        self.lineEdit_matkhau = QtWidgets.QLineEdit(parent=self.ResetFrame)
        self.lineEdit_matkhau.setGeometry(QtCore.QRect(30, 220, 431, 41))
        self.lineEdit_matkhau.setStyleSheet("\n"
"border:2px solid #8EC5B7;\n"
"border-radius:20px;\n"
"padding-left:35px;\n"
"background:white;\n"
"font-family: \"Avenir Next\";\n"
"font-size:15px;")
        self.lineEdit_matkhau.setText("")
        self.lineEdit_matkhau.setObjectName("lineEdit_matkhau")
        self.lb_xacnhan = QtWidgets.QLabel(parent=self.ResetFrame)
        self.lb_xacnhan.setGeometry(QtCore.QRect(30, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lb_xacnhan.setFont(font)
        self.lb_xacnhan.setStyleSheet("color: #4E6E5D;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.lb_xacnhan.setObjectName("lb_xacnhan")
        self.lineEdit_xacnhan = QtWidgets.QLineEdit(parent=self.ResetFrame)
        self.lineEdit_xacnhan.setGeometry(QtCore.QRect(30, 320, 431, 41))
        self.lineEdit_xacnhan.setStyleSheet("\n"
"border:2px solid #8EC5B7;\n"
"border-radius:20px;\n"
"padding-left:35px;\n"
"background:white;\n"
"font-family: \"Avenir Next\";\n"
"font-size:15px;")
        self.lineEdit_xacnhan.setText("")
        self.lineEdit_xacnhan.setObjectName("lineEdit_xacnhan")
        self.pB_ma = QtWidgets.QPushButton(parent=self.ResetFrame)
        self.pB_ma.setGeometry(QtCore.QRect(100, 430, 321, 45))
        self.pB_ma.setMinimumSize(QtCore.QSize(45, 45))
        self.pB_ma.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}\n"
"QPushButton {\n"
"    background-color: #63B995;\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4FA883;\n"
"}\n"
"font-family: \"Avenir Next\";\n"
"")
        self.pB_ma.setObjectName("pB_ma")
        self.label_error = QtWidgets.QLabel(parent=self.ResetFrame)
        self.label_error.setGeometry(QtCore.QRect(50, 370, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: red;\n"
"font-size:12px;")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.btn_eye_password = QtWidgets.QPushButton(parent=self.ResetFrame)
        self.btn_eye_password.setGeometry(QtCore.QRect(410, 230, 31, 21))
        self.btn_eye_password.setText("")
        self.btn_eye_password.setObjectName("btn_eye_password")
        self.btn_eye_confirm = QtWidgets.QPushButton(parent=self.ResetFrame)
        self.btn_eye_confirm.setGeometry(QtCore.QRect(410, 330, 31, 21))
        self.btn_eye_confirm.setText("")
        self.btn_eye_confirm.setObjectName("btn_eye_confirm")
        self.lbl_error = QtWidgets.QLabel(parent=self.ResetFrame)
        self.lbl_error.setGeometry(QtCore.QRect(30, 380, 421, 21))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.lbl_error.setFont(font)
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")

        self.retranslateUi(Reset)
        QtCore.QMetaObject.connectSlotsByName(Reset)

    def retranslateUi(self, Reset):
        _translate = QtCore.QCoreApplication.translate
        Reset.setWindowTitle(_translate("Reset", "Dialog"))
        self.btn_minimize.setText(_translate("Reset", "-"))
        self.btn_maximize.setText(_translate("Reset", "□"))
        self.btn_close.setText(_translate("Reset", "x"))
        self.label_khoiphuc.setText(_translate("Reset", "Khôi phục mật khẩu"))
        self.lineEdit_tendangnhap.setPlaceholderText(_translate("Reset", "Nhập tên đăng nhập mới"))
        self.lb_tendangnhap.setText(_translate("Reset", "      Tên đăng nhập "))
        self.lb_matkhau.setText(_translate("Reset", "Mật khẩu"))
        self.lineEdit_matkhau.setPlaceholderText(_translate("Reset", "Nhập mật khẩu mới"))
        self.lb_xacnhan.setText(_translate("Reset", "Xác nhận mật khẩu"))
        self.lineEdit_xacnhan.setPlaceholderText(_translate("Reset", "Xác nhận lại mật khẩu"))
        self.pB_ma.setText(_translate("Reset", "Đổi mật khẩu"))
