# Form implementation generated from reading ui file 'trang44.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(200, 110, 451, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 421, 261))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 10, 421, 261))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 10, 421, 261))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 430, 111, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px ;         /* bo tròn */\n"
"    font-size: 16px; \n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 430, 161, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px ;         /* bo tròn */\n"
"    font-size: 16px; \n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 430, 131, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px ;         /* bo tròn */\n"
"    font-size: 16px; \n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 20, 451, 80))
        self.frame.setStyleSheet("background-color:#EAF5F0;\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(160, 10, 161, 71))
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(770, 0, 31, 23))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:red;\n"
"                   color:white;\n"
"               }")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(740, 0, 31, 23))
        self.pushButton_5.setStyleSheet(" QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:#E0E0E0;\n"
"               }")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(710, 0, 31, 23))
        self.pushButton_6.setStyleSheet(" QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:#E0E0E0;\n"
"               }")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame.raise_()
        self.tabWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "TỔNG QUAN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "XU HƯỚNG"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "DỰ ĐOÁN"))
        self.pushButton.setText(_translate("MainWindow", "LÀM MỚI"))
        self.pushButton_2.setText(_translate("MainWindow", "XUẤT BÁO CÁO"))
        self.pushButton_3.setText(_translate("MainWindow", "QUAY LẠI"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#aa557f;\">PHÂN TÍCH AI</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
