# Form implementation generated from reading ui file 'trang1.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NhatKyCamXuc(object):
    def setupUi(self, NhatKyCamXuc):
        NhatKyCamXuc.setObjectName("NhatKyCamXuc")
        NhatKyCamXuc.resize(1212, 527)
        NhatKyCamXuc.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=NhatKyCamXuc)
        self.centralwidget.setObjectName("centralwidget")
        self.lblDate = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDate.setGeometry(QtCore.QRect(600, 230, 311, 41))
        self.lblDate.setText("")
        self.lblDate.setObjectName("lblDate")
        self.progressBar_emotion = QtWidgets.QSlider(parent=self.centralwidget)
        self.progressBar_emotion.setGeometry(QtCore.QRect(100, 190, 401, 22))
        self.progressBar_emotion.setStyleSheet("#progressBar_emotion {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    height: 35px;\n"
"    text-align: center;\n"
"    font-family: \"Avenir Next\", Arial, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#progressBar_emotion::chunk {\n"
"    background-color: #7FBF9F;\n"
"    border-radius: 18px;\n"
"    margin: 2px;\n"
"}\n"
"#progressBar_emotion {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    height: 35px;\n"
"    text-align: center;\n"
"    font-family: \"Avenir Next\", Arial, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#progressBar_emotion::chunk {\n"
"    background-color: #7FBF9F;\n"
"    border-radius: 18px;\n"
"    margin: 2px;\n"
"}\n"
" ")
        self.progressBar_emotion.setMaximum(6)
        self.progressBar_emotion.setProperty("value", 3)
        self.progressBar_emotion.setSliderPosition(3)
        self.progressBar_emotion.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar_emotion.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.progressBar_emotion.setTickInterval(1)
        self.progressBar_emotion.setObjectName("progressBar_emotion")
        self.txtNote = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtNote.setGeometry(QtCore.QRect(140, 230, 361, 251))
        self.txtNote.setObjectName("txtNote")
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(530, 90, 181, 41))
        self.btnSave.setStyleSheet("\n"
"       QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnSave.setObjectName("btnSave")
        self.btnToPage3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnToPage3.setGeometry(QtCore.QRect(750, 90, 201, 41))
        self.btnToPage3.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnToPage3.setObjectName("btnToPage3")
        self.btnToPage4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnToPage4.setGeometry(QtCore.QRect(530, 160, 181, 41))
        self.btnToPage4.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnToPage4.setObjectName("btnToPage4")
        self.btnToPage2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnToPage2.setGeometry(QtCore.QRect(750, 160, 201, 41))
        self.btnToPage2.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnToPage2.setObjectName("btnToPage2")
        self.Back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(560, 420, 161, 41))
        self.Back.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.Back.setObjectName("Back")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 131, 31))
        self.label.setStyleSheet("QLabel#ngayLabel, \n"
"QLabel[text=\"Nhập ngày:\"],\n"
"QLabel:contains(\"Nhập ngày\") {\n"
"    background-color: #0066cc !important;  /* màu xanh */\n"
"    color: white !important;                /* chữ trắng */\n"
"    font-family: \"Avenir Next\", Arial, sans-serif !important;\n"
"    border-radius: 18px !important;         /* bo tròn */\n"
"    font-size: 16px !important;\n"
"    font-weight: bold !important;\n"
"    padding: 10px !important;\n"
"    border: none !important;\n"
"}\n"
"\n"
"")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(230, 30, 281, 51))
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(530, 260, 331, 131))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 140, 51, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(186, 150, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 150, 47, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 150, 47, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 140, 61, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(446, 140, 51, 51))
        self.label_7.setObjectName("label_7")
        NhatKyCamXuc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NhatKyCamXuc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1212, 21))
        self.menubar.setObjectName("menubar")
        NhatKyCamXuc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NhatKyCamXuc)
        self.statusbar.setObjectName("statusbar")
        NhatKyCamXuc.setStatusBar(self.statusbar)

        self.retranslateUi(NhatKyCamXuc)
        QtCore.QMetaObject.connectSlotsByName(NhatKyCamXuc)

    def retranslateUi(self, NhatKyCamXuc):
        _translate = QtCore.QCoreApplication.translate
        NhatKyCamXuc.setWindowTitle(_translate("NhatKyCamXuc", "MainWindow"))
        self.txtNote.setHtml(_translate("NhatKyCamXuc", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#0f1115;\">📝 NHẬP GHI CHÚ CỦA BẠN:</span></p></body></html>"))
        self.btnSave.setText(_translate("NhatKyCamXuc", "💾 LƯU CẢM XÚC"))
        self.btnToPage3.setText(_translate("NhatKyCamXuc", "📈:BIỂU ĐỒ CẢM XÚC"))
        self.btnToPage4.setText(_translate("NhatKyCamXuc", "🔍PHÂN TÍCH AI"))
        self.btnToPage2.setText(_translate("NhatKyCamXuc", "📋LỊCH CẢM XÚC"))
        self.Back.setText(_translate("NhatKyCamXuc", "BACK"))
        self.label.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#161616;\">📅 Nhập ngày:</span></p></body></html>"))
        self.label_2.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😢</span></p></body></html>"))
        self.label_3.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😞</span></p></body></html>"))
        self.label_4.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😐</span></p></body></html>"))
        self.label_5.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">🙂</span></p></body></html>"))
        self.label_6.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😊</span></p></body></html>"))
        self.label_7.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😍</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NhatKyCamXuc = QtWidgets.QMainWindow()
    ui = Ui_NhatKyCamXuc()
    ui.setupUi(NhatKyCamXuc)
    NhatKyCamXuc.show()
    sys.exit(app.exec())
