# Form implementation generated from reading ui file 'trang11.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NhatKyCamXuc(object):
    def setupUi(self, NhatKyCamXuc):
        NhatKyCamXuc.setObjectName("NhatKyCamXuc")
        NhatKyCamXuc.resize(1353, 623)
        NhatKyCamXuc.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=NhatKyCamXuc)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 90, 901, 461))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(parent=self.frame_3)
        self.frame.setGeometry(QtCore.QRect(30, 40, 351, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"/* Lưu ý: QLabel không có trạng thái \"pressed\" như QPushButton\n"
"   Nếu muốn hiệu ứng khi click, bạn cần dùng mousePressEvent */\n"
"\n"
"")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frame)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.progressBar_emotion = QtWidgets.QSlider(parent=self.frame_3)
        self.progressBar_emotion.setGeometry(QtCore.QRect(20, 190, 401, 22))
        self.progressBar_emotion.setStyleSheet("#progressBar_emotion {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    height: 35px;\n"
"    text-align: center;\n"
"    font-family: \"Avenir Next\", Arial, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#progressBar_emotion::chunk {\n"
"    background-color: #7FBF9F;\n"
"    border-radius: 18px;\n"
"    margin: 2px;\n"
"}\n"
"#progressBar_emotion {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    height: 35px;\n"
"    text-align: center;\n"
"    font-family: \"Avenir Next\", Arial, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#progressBar_emotion::chunk {\n"
"    background-color: #7FBF9F;\n"
"    border-radius: 18px;\n"
"    margin: 2px;\n"
"}\n"
" ")
        self.progressBar_emotion.setMaximum(6)
        self.progressBar_emotion.setProperty("value", 3)
        self.progressBar_emotion.setSliderPosition(3)
        self.progressBar_emotion.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar_emotion.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.progressBar_emotion.setTickInterval(1)
        self.progressBar_emotion.setObjectName("progressBar_emotion")
        self.txtNote = QtWidgets.QTextEdit(parent=self.frame_3)
        self.txtNote.setGeometry(QtCore.QRect(30, 220, 361, 251))
        self.txtNote.setObjectName("txtNote")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(370, 130, 51, 51))
        self.label_7.setObjectName("label_7")
        self.btnToPage3 = QtWidgets.QPushButton(parent=self.frame_3)
        self.btnToPage3.setGeometry(QtCore.QRect(670, 50, 201, 41))
        self.btnToPage3.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnToPage3.setObjectName("btnToPage3")
        self.btnSave = QtWidgets.QPushButton(parent=self.frame_3)
        self.btnSave.setGeometry(QtCore.QRect(470, 50, 181, 41))
        self.btnSave.setStyleSheet("\n"
"       QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnSave.setObjectName("btnSave")
        self.btnToPage2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.btnToPage2.setGeometry(QtCore.QRect(660, 100, 201, 41))
        self.btnToPage2.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnToPage2.setObjectName("btnToPage2")
        self.btnToPage4 = QtWidgets.QPushButton(parent=self.frame_3)
        self.btnToPage4.setGeometry(QtCore.QRect(470, 100, 181, 41))
        self.btnToPage4.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnToPage4.setObjectName("btnToPage4")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(300, 130, 61, 51))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(240, 140, 47, 31))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(170, 140, 47, 31))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(110, 140, 61, 31))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 51, 51))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame_3)
        self.textEdit.setGeometry(QtCore.QRect(470, 230, 331, 131))
        self.textEdit.setObjectName("textEdit")
        self.Back = QtWidgets.QPushButton(parent=self.frame_3)
        self.Back.setGeometry(QtCore.QRect(490, 380, 161, 41))
        self.Back.setStyleSheet("   QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 18px;         /* bo tròn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.Back.setObjectName("Back")
        self.label_7.raise_()
        self.label_6.raise_()
        self.frame.raise_()
        self.progressBar_emotion.raise_()
        self.txtNote.raise_()
        self.btnToPage3.raise_()
        self.btnSave.raise_()
        self.btnToPage2.raise_()
        self.btnToPage4.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.textEdit.raise_()
        self.Back.raise_()
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(230, 10, 901, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 901, 81))
        self.label_9.setStyleSheet("background-color:#EAF5F0;\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1320, 0, 31, 31))
        self.pushButton.setStyleSheet("\n"
"               QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:red;\n"
"                   color:white;\n"
"               }")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1290, 0, 31, 31))
        self.pushButton_2.setStyleSheet("\n"
"               QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:#E0E0E0;\n"
"               }\n"
"               ")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1260, 0, 31, 31))
        self.pushButton_3.setStyleSheet("  QPushButton{\n"
"                   font-size:18px;\n"
"                   border:none;\n"
"                   background:transparent;\n"
"               }\n"
"               QPushButton:hover{\n"
"                   background:#E0E0E0;\n"
"               }")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        NhatKyCamXuc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NhatKyCamXuc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 21))
        self.menubar.setObjectName("menubar")
        NhatKyCamXuc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NhatKyCamXuc)
        self.statusbar.setObjectName("statusbar")
        NhatKyCamXuc.setStatusBar(self.statusbar)

        self.retranslateUi(NhatKyCamXuc)
        QtCore.QMetaObject.connectSlotsByName(NhatKyCamXuc)

    def retranslateUi(self, NhatKyCamXuc):
        _translate = QtCore.QCoreApplication.translate
        NhatKyCamXuc.setWindowTitle(_translate("NhatKyCamXuc", "MainWindow"))
        self.label.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">📅 Nhập ngày:</span></p></body></html>"))
        self.txtNote.setHtml(_translate("NhatKyCamXuc", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:8pt; color:#0f1115;\">📝 NHẬP GHI CHÚ CỦA BẠN:</span></p></body></html>"))
        self.label_7.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😍</span></p></body></html>"))
        self.btnToPage3.setText(_translate("NhatKyCamXuc", "📈BIỂU ĐỒ CẢM XÚC"))
        self.btnSave.setText(_translate("NhatKyCamXuc", "💾 LƯU CẢM XÚC"))
        self.btnToPage2.setText(_translate("NhatKyCamXuc", "📋LỊCH CẢM XÚC"))
        self.btnToPage4.setText(_translate("NhatKyCamXuc", "🔍PHÂN TÍCH AI"))
        self.label_6.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😊</span></p></body></html>"))
        self.label_5.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">🙂</span></p></body></html>"))
        self.label_4.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😐</span></p></body></html>"))
        self.label_3.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😞</span></p></body></html>"))
        self.label_2.setText(_translate("NhatKyCamXuc", "<html><head/><body><p><span style=\" font-size:18pt;\">😢</span></p></body></html>"))
        self.Back.setText(_translate("NhatKyCamXuc", "QUAY LẠI"))
        self.label_9.setText(_translate("NhatKyCamXuc", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#005500;\">NHẬT KÝ CẢM XÚC </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NhatKyCamXuc = QtWidgets.QMainWindow()
    ui = Ui_NhatKyCamXuc()
    ui.setupUi(NhatKyCamXuc)
    NhatKyCamXuc.show()
    sys.exit(app.exec())
