# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1470, 863)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/Mar 2, 2026 at 01_58_50 AM.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/* ===== GLOBAL ===== */\n"
"\n"
"QMainWindow, QWidget {\n"
"    background-color: #eef5f3;\n"
"    font-family: \"SF Pro Display\", \"Segoe UI\", Arial;\n"
"    font-size: 14px;\n"
"    color: #2c3e3a;\n"
"}\n"
"\n"
"\n"
"/* ===== TITLE FRAME ===== */\n"
"\n"
"#title_frame {\n"
"    background-color: #e4f0ec;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#title_frame QLabel {\n"
"    color: #4aa485;\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"\n"
"/* ===== SECTION HEADER ===== */\n"
"\n"
"QLabel {\n"
"    color: #4aa485;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"\n"
"/* ===== INPUTS ===== */\n"
"\n"
"QLineEdit,\n"
"QComboBox,\n"
"QSpinBox {\n"
"    background: white;\n"
"    border: 2px solid #d7e7e2;\n"
"    border-radius: 8px;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus,\n"
"QSpinBox:focus {\n"
"    border: 2px solid #5FB79B;\n"
"}\n"
"\n"
"\n"
"/* ===== COMBOBOX ===== */\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"\n"
"/* ===== TOOLBOX ===== */\n"
"\n"
"QToolBox::tab {\n"
"    background: #e4f0ec;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background: #5FB79B;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"/* ===== QUESTION BOX ===== */\n"
"\n"
"QFrame {\n"
"    background: white;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #d9e8e3;\n"
"}\n"
"\n"
"\n"
"/* ===== QUESTION TITLE BAR ===== */\n"
"\n"
"QLabel#questionTitle {\n"
"    background: #5FB79B;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"/* ===== RADIO BUTTON ===== */\n"
"\n"
"QRadioButton {\n"
"    spacing: 8px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 2px solid #9dcfc0;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid #5FB79B;\n"
"    border-radius: 8px;\n"
"    background: #5FB79B;\n"
"}\n"
"\n"
"\n"
"/* ===== MAIN BUTTON ===== */\n"
"\n"
"QPushButton {\n"
"    background-color: #5FB79B;\n"
"    border-radius: 20px;\n"
"    padding: 10px 20px;\n"
"    color: white;\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4aa485;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c8e74;\n"
"}\n"
"\n"
"\n"
"/* ===== LARGE API BUTTON ===== */\n"
"\n"
"QPushButton#fetchButton {\n"
"    font-size: 18px;\n"
"    padding: 14px;\n"
"}\n"
"\n"
"\n"
"/* ===== SECONDARY BUTTON ===== */\n"
"\n"
"QPushButton#retryButton {\n"
"    background-color: #9fd7c6;\n"
"}\n"
"\n"
"QPushButton#retryButton:hover {\n"
"    background-color: #8acbb7;\n"
"}\n"
"\n"
"\n"
"/* ===== PROGRESS BADGE ===== */\n"
"\n"
"QLabel#progressLabel {\n"
"    background: #5FB79B;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"/* ===== TEXT QUESTION AREA ===== */\n"
"\n"
"QTextEdit {\n"
"    background: #f7fbf9;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #d8ebe5;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_frame.setGeometry(QtCore.QRect(240, 20, 821, 81))
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.label_2 = QtWidgets.QLabel(parent=self.title_frame)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color:#5FA382;\n"
"    font-family: Fredoka;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.title_frame)
        self.label.setGeometry(QtCore.QRect(280, 10, 91, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/15ef6990-09e6-4771-937d-8241240567fc.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.toolBox = QtWidgets.QToolBox(parent=self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(240, 150, 821, 621))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 817, 549))
        self.page.setObjectName("page")
        self.db_frame = QtWidgets.QFrame(parent=self.page)
        self.db_frame.setGeometry(QtCore.QRect(40, 20, 711, 201))
        self.db_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.db_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.db_frame.setObjectName("db_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.db_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.db_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(parent=self.db_frame)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(50)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.db_frame)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.db_frame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.db_frame)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.db_frame)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.db_frame)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.db_frame)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.db_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(15, 20, 15, 9)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnFetch = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnFetch.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnFetch.setObjectName("btnFetch")
        self.gridLayout_2.addWidget(self.btnFetch, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 4)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 817, 549))
        self.page_2.setObjectName("page_2")
        self.questions_frame = QtWidgets.QFrame(parent=self.page_2)
        self.questions_frame.setGeometry(QtCore.QRect(19, 14, 781, 521))
        self.questions_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.questions_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.questions_frame.setObjectName("questions_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.questions_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info_frame = QtWidgets.QFrame(parent=self.questions_frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.info_frame.setObjectName("info_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.info_frame)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.question_count_label = QtWidgets.QLabel(parent=self.info_frame)
        self.question_count_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.question_count_label.setObjectName("question_count_label")
        self.horizontalLayout.addWidget(self.question_count_label)
        self.verticalLayout_3.addWidget(self.info_frame)
        self.frame_5 = QtWidgets.QFrame(parent=self.questions_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_5)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.answer_frame = QtWidgets.QFrame(parent=self.frame_5)
        self.answer_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.answer_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.answer_frame.setObjectName("answer_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.answer_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio4 = QtWidgets.QRadioButton(parent=self.answer_frame)
        self.radio4.setObjectName("radio4")
        self.verticalLayout.addWidget(self.radio4)
        self.radio1 = QtWidgets.QRadioButton(parent=self.answer_frame)
        self.radio1.setObjectName("radio1")
        self.verticalLayout.addWidget(self.radio1)
        self.radio2 = QtWidgets.QRadioButton(parent=self.answer_frame)
        self.radio2.setObjectName("radio2")
        self.verticalLayout.addWidget(self.radio2)
        self.radio3 = QtWidgets.QRadioButton(parent=self.answer_frame)
        self.radio3.setObjectName("radio3")
        self.verticalLayout.addWidget(self.radio3)
        self.verticalLayout_2.addWidget(self.answer_frame)
        self.verticalLayout_3.addWidget(self.frame_5)
        spacerItem = QtWidgets.QSpacerItem(18, 42, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.function_frame = QtWidgets.QFrame(parent=self.questions_frame)
        self.function_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.function_frame.setObjectName("function_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.function_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.function_frame)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.btnCheck = QtWidgets.QPushButton(parent=self.function_frame)
        self.btnCheck.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}\n"
"")
        self.btnCheck.setObjectName("btnCheck")
        self.horizontalLayout_3.addWidget(self.btnCheck)
        self.btnNext = QtWidgets.QPushButton(parent=self.function_frame)
        self.btnNext.setStyleSheet("QPushButton {\n"
"    background-color: #7FBF9F;   /* xanh nhạt */\n"
"    color: white;                /* chữ trắng */\n"
"    border-radius: 22px;         /* bo tròn */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5FA382;   /* xanh đậm khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E8C70;   /* xanh đậm hơn khi bấm */\n"
"}")
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_3.addWidget(self.btnNext)
        self.verticalLayout_3.addWidget(self.function_frame)
        self.toolBox.addItem(self.page_2, "")
        self.maximizeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.maximizeButton.setGeometry(QtCore.QRect(1410, 0, 31, 32))
        self.maximizeButton.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:black;\n"
"                       }\n"
"QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }")
        self.maximizeButton.setObjectName("maximizeButton")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(1440, 0, 31, 32))
        self.closeButton.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:black;\n"
"                       }\n"
"QPushButton:hover{\n"
"                           background:red;\n"
"                       }")
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(1380, 0, 31, 32))
        self.minimizeButton.setStyleSheet("QPushButton{\n"
"                           font-size:18px;\n"
"                           border:none;\n"
"                           background:black;\n"
"                       }\n"
"                       QPushButton:hover{\n"
"                           background:#E0E0E0;\n"
"                       }\n"
"")
        self.minimizeButton.setObjectName("minimizeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1470, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz App"))
        self.label_2.setText(_translate("MainWindow", "Quiz Application"))
        self.label_3.setText(_translate("MainWindow", "Số lượng câu hỏi"))
        self.label_5.setText(_translate("MainWindow", "Độ khó"))
        self.label_4.setText(_translate("MainWindow", "Môn học"))
        self.label_6.setText(_translate("MainWindow", "Loại câu hỏi"))
        self.btnFetch.setText(_translate("MainWindow", "Lấy câu hỏi mới"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Cài đặt"))
        self.label_7.setText(_translate("MainWindow", "Môn học"))
        self.label_8.setText(_translate("MainWindow", "Độ khó"))
        self.question_count_label.setText(_translate("MainWindow", "10/50"))
        self.label_10.setText(_translate("MainWindow", "Câu hỏi:"))
        self.radio4.setText(_translate("MainWindow", "RadioButton"))
        self.radio1.setText(_translate("MainWindow", "RadioButton"))
        self.radio2.setText(_translate("MainWindow", "RadioButton"))
        self.radio3.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton.setText(_translate("MainWindow", "Thử lại"))
        self.btnCheck.setText(_translate("MainWindow", "Kiểm tra"))
        self.btnNext.setText(_translate("MainWindow", "Tiếp tục"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Câu hỏi"))
        self.maximizeButton.setText(_translate("MainWindow", "□"))
        self.closeButton.setText(_translate("MainWindow", "✕"))
        self.minimizeButton.setText(_translate("MainWindow", "─"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
